//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision_System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vision_System.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string RtAboutButton {
            get {
                return ResourceManager.GetString("RtAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string RtAboutTitle {
            get {
                return ResourceManager.GetString("RtAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPT.
        /// </summary>
        internal static string RtAccept {
            get {
                return ResourceManager.GetString("RtAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string RtAdministrator {
            get {
                return ResourceManager.GetString("RtAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application generated on {0} by version {1} of the Cognex Application Wizard.
        /// </summary>
        internal static string RtAppGeneratedInfo {
            get {
                return ResourceManager.GetString("RtAppGeneratedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Options....
        /// </summary>
        internal static string RtAppOptions {
            get {
                return ResourceManager.GetString("RtAppOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Options.
        /// </summary>
        internal static string RtAppOptionsTitle {
            get {
                return ResourceManager.GetString("RtAppOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RtCancel {
            get {
                return ResourceManager.GetString("RtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History Queues.
        /// </summary>
        internal static string RtClearQueues {
            get {
                return ResourceManager.GetString("RtClearQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration....
        /// </summary>
        internal static string RtConfigurationButton {
            get {
                return ResourceManager.GetString("RtConfigurationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string RtConfigurationTitle {
            get {
                return ResourceManager.GetString("RtConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        internal static string RtConfirmPassword {
            get {
                return ResourceManager.GetString("RtConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current IO state:.
        /// </summary>
        internal static string RtCurrentIOState {
            get {
                return ResourceManager.GetString("RtCurrentIOState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current login:.
        /// </summary>
        internal static string RtCurrentLogin {
            get {
                return ResourceManager.GetString("RtCurrentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none: default passwords in use&gt;.
        /// </summary>
        internal static string RtDefaultPasswords {
            get {
                return ResourceManager.GetString("RtDefaultPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable image display.
        /// </summary>
        internal static string RtEnableDisplay {
            get {
                return ResourceManager.GetString("RtEnableDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go online at application startup.
        /// </summary>
        internal static string RtEnableIOAtStartup {
            get {
                return ResourceManager.GetString("RtEnableIOAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter {0} Password.
        /// </summary>
        internal static string RtEnterPassword {
            get {
                return ResourceManager.GetString("RtEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string RtError {
            get {
                return ResourceManager.GetString("RtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error loading .vpp file:.
        /// </summary>
        internal static string RtErrorLoadingVpp {
            get {
                return ResourceManager.GetString("RtErrorLoadingVpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error saving .vpp file ({0}):.
        /// </summary>
        internal static string RtErrorSavingVpp {
            get {
                return ResourceManager.GetString("RtErrorSavingVpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vpp file cannot be saved while jobs are running..
        /// </summary>
        internal static string RtErrorSavingVpp_Running {
            get {
                return ResourceManager.GetString("RtErrorSavingVpp_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Options.
        /// </summary>
        internal static string RtGroupDisplayOptions {
            get {
                return ResourceManager.GetString("RtGroupDisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Options.
        /// </summary>
        internal static string RtGroupIOOptions {
            get {
                return ResourceManager.GetString("RtGroupIOOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Options.
        /// </summary>
        internal static string RtGroupQueueOptions {
            get {
                return ResourceManager.GetString("RtGroupQueueOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An image queue overrun has occurred for {0}.
        /// </summary>
        internal static string RtImageQueueOverrun {
            get {
                return ResourceManager.GetString("RtImageQueueOverrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string RtInvalidPassword {
            get {
                return ResourceManager.GetString("RtInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is incorrect..
        /// </summary>
        internal static string RtInvalidPassword2 {
            get {
                return ResourceManager.GetString("RtInvalidPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password file {0}.
        /// </summary>
        internal static string RtInvalidPasswordFile {
            get {
                return ResourceManager.GetString("RtInvalidPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Image.
        /// </summary>
        internal static string RtLiveImageButton {
            get {
                return ResourceManager.GetString("RtLiveImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string RtLoadFileButton {
            get {
                return ResourceManager.GetString("RtLoadFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional details available..
        /// </summary>
        internal static string RtNoDetails {
            get {
                return ResourceManager.GetString("RtNoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none&gt;.
        /// </summary>
        internal static string RtNoFile {
            get {
                return ResourceManager.GetString("RtNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string RtOffline {
            get {
                return ResourceManager.GetString("RtOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string RtOK {
            get {
                return ResourceManager.GetString("RtOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string RtOnline {
            get {
                return ResourceManager.GetString("RtOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred trying to open {0}:.
        /// </summary>
        internal static string RtOpenFileError {
            get {
                return ResourceManager.GetString("RtOpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string RtOperator {
            get {
                return ResourceManager.GetString("RtOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string RtPassword {
            get {
                return ResourceManager.GetString("RtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickBuild....
        /// </summary>
        internal static string RtQuickBuild {
            get {
                return ResourceManager.GetString("RtQuickBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickBuild.
        /// </summary>
        internal static string RtQuickBuildTitle {
            get {
                return ResourceManager.GetString("RtQuickBuildTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REJECT.
        /// </summary>
        internal static string RtReject {
            get {
                return ResourceManager.GetString("RtReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;not available&gt;.
        /// </summary>
        internal static string RtResultNotAvailable {
            get {
                return ResourceManager.GetString("RtResultNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Continuously.
        /// </summary>
        internal static string RtRunContinuouslyButton {
            get {
                return ResourceManager.GetString("RtRunContinuouslyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Once.
        /// </summary>
        internal static string RtRunOnceButton {
            get {
                return ResourceManager.GetString("RtRunOnceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        internal static string RtSaveSettingsButton {
            get {
                return ResourceManager.GetString("RtSaveSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the current QuickBuild settings to {0}?.
        /// </summary>
        internal static string RtSaveSettingsText {
            get {
                return ResourceManager.GetString("RtSaveSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the current QuickBuild settings to {0}?  If you answer No, the settings can be saved at a later time using the {1} button..
        /// </summary>
        internal static string RtSaveSettingsTextAfterConfig {
            get {
                return ResourceManager.GetString("RtSaveSettingsTextAfterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string RtSaveSettingsTitle {
            get {
                return ResourceManager.GetString("RtSaveSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Passwords....
        /// </summary>
        internal static string RtSetPasswords {
            get {
                return ResourceManager.GetString("RtSetPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Passwords.
        /// </summary>
        internal static string RtSetPasswordsTitle {
            get {
                return ResourceManager.GetString("RtSetPasswordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string RtSettingPasswordButton {
            get {
                return ResourceManager.GetString("RtSettingPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors:.
        /// </summary>
        internal static string RtStatsAcqErrorCount {
            get {
                return ResourceManager.GetString("RtStatsAcqErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overruns:.
        /// </summary>
        internal static string RtStatsAcqOverrunCount {
            get {
                return ResourceManager.GetString("RtStatsAcqOverrunCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition Results.
        /// </summary>
        internal static string RtStatsAcquisitionResultsGroup {
            get {
                return ResourceManager.GetString("RtStatsAcquisitionResultsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Acquisitions:.
        /// </summary>
        internal static string RtStatsAcquisitions {
            get {
                return ResourceManager.GetString("RtStatsAcquisitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepts:.
        /// </summary>
        internal static string RtStatsJobAcceptCount {
            get {
                return ResourceManager.GetString("RtStatsJobAcceptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors:.
        /// </summary>
        internal static string RtStatsJobErrorCount {
            get {
                return ResourceManager.GetString("RtStatsJobErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Iterations:.
        /// </summary>
        internal static string RtStatsJobIterations {
            get {
                return ResourceManager.GetString("RtStatsJobIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejects:.
        /// </summary>
        internal static string RtStatsJobRejectCount {
            get {
                return ResourceManager.GetString("RtStatsJobRejectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Results.
        /// </summary>
        internal static string RtStatsJobResultsGroup {
            get {
                return ResourceManager.GetString("RtStatsJobResultsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Throughput:.
        /// </summary>
        internal static string RtStatsJobThroughput {
            get {
                return ResourceManager.GetString("RtStatsJobThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Throughput.
        /// </summary>
        internal static string RtStatsJobThroughputGroup {
            get {
                return ResourceManager.GetString("RtStatsJobThroughputGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings:.
        /// </summary>
        internal static string RtStatsJobWarningCount {
            get {
                return ResourceManager.GetString("RtStatsJobWarningCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string RtStatsNA {
            get {
                return ResourceManager.GetString("RtStatsNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Statistics.
        /// </summary>
        internal static string RtStatsPageTitle {
            get {
                return ResourceManager.GetString("RtStatsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string RtStatsPercent {
            get {
                return ResourceManager.GetString("RtStatsPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per sec.
        /// </summary>
        internal static string RtStatsPerSecond {
            get {
                return ResourceManager.GetString("RtStatsPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Statistics.
        /// </summary>
        internal static string RtStatsReset {
            get {
                return ResourceManager.GetString("RtStatsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Statistics For All Jobs.
        /// </summary>
        internal static string RtStatsResetAll {
            get {
                return ResourceManager.GetString("RtStatsResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Throughput:.
        /// </summary>
        internal static string RtStatsThroughput {
            get {
                return ResourceManager.GetString("RtStatsThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max:.
        /// </summary>
        internal static string RtStatsThroughputMax {
            get {
                return ResourceManager.GetString("RtStatsThroughputMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min:.
        /// </summary>
        internal static string RtStatsThroughputMin {
            get {
                return ResourceManager.GetString("RtStatsThroughputMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting....
        /// </summary>
        internal static string RtStatsWaiting {
            get {
                return ResourceManager.GetString("RtStatsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string RtStopButton {
            get {
                return ResourceManager.GetString("RtStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Live.
        /// </summary>
        internal static string RtStopLiveButton {
            get {
                return ResourceManager.GetString("RtStopLiveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en (English).
        /// </summary>
        internal static string RtStringLanguage {
            get {
                return ResourceManager.GetString("RtStringLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string RtSupervisor {
            get {
                return ResourceManager.GetString("RtSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is OFFLINE.
        /// </summary>
        internal static string RtSystemOffline {
            get {
                return ResourceManager.GetString("RtSystemOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is ONLINE.
        /// </summary>
        internal static string RtSystemOnline {
            get {
                return ResourceManager.GetString("RtSystemOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard.
        /// </summary>
        internal static string RtTemplateName {
            get {
                return ResourceManager.GetString("RtTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error -.
        /// </summary>
        internal static string RtUnexpectedErrorQB {
            get {
                return ResourceManager.GetString("RtUnexpectedErrorQB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains an acquisition configuration that could not be initialized (due to missing camera or frame grabber, hardware in use, or a security violation).  Please correct the problem or reconfigure the acquisition properties before running the job..
        /// </summary>
        internal static string RtUninitializedAcq {
            get {
                return ResourceManager.GetString("RtUninitializedAcq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using about.txt file:.
        /// </summary>
        internal static string RtUsingAbout {
            get {
                return ResourceManager.GetString("RtUsingAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using passwords.txt file:.
        /// </summary>
        internal static string RtUsingPasswords {
            get {
                return ResourceManager.GetString("RtUsingPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using .vpp file:.
        /// </summary>
        internal static string RtUsingVpp {
            get {
                return ResourceManager.GetString("RtUsingVpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vpp file not found ({0} or {1})..
        /// </summary>
        internal static string RtVppNotFound {
            get {
                return ResourceManager.GetString("RtVppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string RtWarning {
            get {
                return ResourceManager.GetString("RtWarning", resourceCulture);
            }
        }
    }
}
